AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.6
  Exclude:
    - '**/Guardfile'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'dotloop.gemspec'
Documentation:
  Enabled: false
Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'
Metrics/LineLength:
  Max: 120
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/MethodLength:
  CountComments: false
  Max: 15
Style/RaiseArgs:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
